[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm -F
priority=10
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
priority=20
autostart=true
autorestart=true

[program:queue]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=120
priority=30
autostart=true
autorestart=true
user=www-data
